/**
 * Agent Manager - SmartAgent lifecycle management
 *
 * Builds and manages SmartAgent instances using SmartAgentBuilder.
 * Configuration comes from environment variables (set via mta.yaml or CF CLI).
 *
 * Architecture:
 * - SmartAgentBuilder wires together: LLM, MCP, RAG, resilience, caching, metrics
 * - LLM: SAP AI Core via sap-ai-sdk provider
 * - MCP: Embedded EmbeddableMcpServer (in-process, no HTTP overhead)
 * - RAG: FallbackRag(VectorRag → InMemoryRag) with CircuitBreakerEmbedder
 * - RAG quality: LlmQueryExpander (synonym expansion) + LlmReranker (semantic re-scoring)
 * - Resilience: CircuitBreaker for LLM + embedder failures
 * - Caching: ToolCache for deduplication, SessionManager for token budget
 * - Metrics: InMemoryMetrics for request/tool/RAG/LLM counters and latencies
 */

import { AsyncLocalStorage } from 'node:async_hooks';
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { HandlerContext } from '@mcp-abap-adt/core/handlers';
import {
  CompactHandlersGroup,
  HandlerExporter,
  HighLevelHandlersGroup,
  LowLevelHandlersGroup,
  ReadOnlyHandlersGroup,
  SearchHandlersGroup,
  SystemHandlersGroup,
} from '@mcp-abap-adt/core/handlers';
import { setSystemContext } from '@mcp-abap-adt/core/utils';
import {
  type CallOptions,
  CircuitBreaker,
  CircuitBreakerEmbedder,
  ClineClientAdapter,
  FallbackLlmCallStrategy,
  FallbackRag,
  InMemoryRag,
  IntentEnricher,
  type IQueryEmbedding,
  type IRag,
  type IRagBackendWriter,
  type IRagEditor,
  type IRequestLogger,
  type ISubAgent,
  NoopDocumentEnricher,
  type RagMetadata,
  type RagResult,
  ToolCache,
  TranslatePreprocessor,
  VectorRag,
} from '@mcp-abap-adt/llm-agent';
import {
  DagPlanInterpreter,
  InMemoryMetrics,
  makeLlm,
  SessionManager,
  SmartAgentBuilder,
  type SmartAgentHandle,
  SmartAgentSubAgent,
} from '@mcp-abap-adt/llm-agent-libs';
import {
  MCPClientWrapper,
  McpClientAdapter,
} from '@mcp-abap-adt/llm-agent-mcp';
import { OpenAiEmbedder } from '@mcp-abap-adt/openai-embedder';
import cds from '@sap/cds';

import { z } from 'zod';
import { type AgentConfig, getAgentConfig } from './agent-config';
import { FixedExecutorPlanner } from './lib/fixed-executor-planner';
import { NoticeFinalizer } from './lib/notice-finalizer';
import { RecordingRequestLogger } from './lib/recording-request-logger';

// ---------------------------------------------------------------------------
// Tool intent cache — pre-generated by tools/generate-tool-intents.ts
// ---------------------------------------------------------------------------
// Maps tool name → { text, enriched } where enriched = text + Intent: keywords.
// When cache exists, IntentEnricher is replaced with NoopDocumentEnricher
// and enriched text is passed directly to upsert (no LLM calls at startup).
// ---------------------------------------------------------------------------
let toolIntentCache: Record<string, { text: string; enriched: string }> | null =
  null;

function getToolIntentCache(): typeof toolIntentCache {
  if (toolIntentCache !== undefined && toolIntentCache !== null)
    return toolIntentCache;
  const cachePath = path.resolve(__dirname, 'tool-intents.json');
  try {
    if (fs.existsSync(cachePath)) {
      const parsed = JSON.parse(fs.readFileSync(cachePath, 'utf-8'));
      toolIntentCache = parsed;
      cds.log('agent-manager').info('Loaded tool intent cache', {
        entries: Object.keys(parsed).length,
      });
    } else {
      toolIntentCache = null;
    }
  } catch {
    toolIntentCache = null;
  }
  return toolIntentCache;
}

// ---------------------------------------------------------------------------
// ExpositionFilteringRag — wraps tools store with role-based filtering
// ---------------------------------------------------------------------------
// Tools are vectorized with metadata.exposition = group name (readonly, high, etc.).
// On query, strips the user/destination namespace (tools have no namespace) but
// post-filters results to only return tools whose exposition is in the caller's
// allowed set (from ragFilter.exposition).
// If ragFilter.exposition is not set, all tools are returned (backwards compat).
// ---------------------------------------------------------------------------

// Cap how many `skill:*` entries a single RAG query may surface. Skills and tools
// live in the SAME shared store and compete for the same top-K, so without a cap a
// RAP prompt (all 18 skills are RAP-adjacent) fills most of the top-K with skills and
// starves tool selection — observed live: 12 of 15 slots were skills. We give tools
// their full k and limit skills to the top-N by score. Env-tunable
// (`LLM_AGENT_SKILL_RAG_K`, default 3); 0 disables skill injection.
const SKILL_RAG_K = (() => {
  const parsed = Number(process.env.LLM_AGENT_SKILL_RAG_K);
  return Number.isFinite(parsed) ? Math.max(0, Math.trunc(parsed)) : 3;
})();

const isSkillId = (id: unknown): boolean =>
  typeof id === 'string' && id.startsWith('skill:');

export class ExpositionFilteringRag implements IRag, IRagEditor {
  constructor(private inner: IRag) {}

  // Skill ids (`skill:<name>`) already vectorized into THIS shared store. The
  // llm-agent builder re-runs its skill-vectorization loop on every build(), and
  // buildAgentForDestination calls build() once per destination against the SAME
  // shared store — so without this, the 18 skills get re-embedded N times
  // (VectorRag.upsert embeds first, then idempotent-replaces by id), reintroducing
  // embedding calls on the deliberately embedding-free cold-start path (v6.21.0).
  // The text for a given skill id is fixed within a process, so a second upsert of
  // the same id is pure waste — skip it. delete/clear reset the guard so an edited
  // skill re-vectorizes.
  private readonly vectorizedSkillIds = new Set<string>();

  async upsert(
    text: string,
    metadata: Record<string, unknown>,
    options?: CallOptions,
  ) {
    const writer = this.inner.writer?.();
    if (!writer) throw new Error('Inner RAG is not editable');
    const { id: rawId, ...rest } = metadata;
    const id = typeof rawId === 'string' ? rawId : '';
    if (!id) throw new Error('metadata.id is required for upsert');
    const res = await writer.upsertRaw(id, text, rest, options);
    if (!res.ok) return res;
    return { ok: true as const, value: { id } };
  }

  async deleteById(id: string, options?: CallOptions) {
    const writer = this.inner.writer?.();
    if (!writer) throw new Error('Inner RAG is not editable');
    return writer.deleteByIdRaw(id, options);
  }

  async getById(id: string, options?: CallOptions) {
    return this.inner.getById(id, options);
  }

  writer(): IRagBackendWriter | undefined {
    const inner = this.inner.writer?.();
    if (!inner) return undefined;
    const seen = this.vectorizedSkillIds;
    // Dedup skill:* re-vectorization (see vectorizedSkillIds above). Everything
    // else passes straight through.
    return {
      async upsertRaw(id, text, metadata, options) {
        if (id.startsWith('skill:') && seen.has(id)) {
          return { ok: true as const, value: undefined };
        }
        const res = await inner.upsertRaw(id, text, metadata, options);
        if (res.ok && id.startsWith('skill:')) seen.add(id);
        return res;
      },
      async deleteByIdRaw(id, options) {
        if (id.startsWith('skill:')) seen.delete(id);
        return inner.deleteByIdRaw(id, options);
      },
      ...(inner.clearAll && {
        clearAll: async () => {
          seen.clear();
          // biome-ignore lint/style/noNonNullAssertion: guarded by the spread condition
          return inner.clearAll!();
        },
      }),
      ...(inner.upsertPrecomputedRaw && {
        upsertPrecomputedRaw: async (
          id: string,
          text: string,
          vector: number[],
          metadata: RagMetadata,
          options?: CallOptions,
        ) => {
          // biome-ignore lint/style/noNonNullAssertion: guarded by the spread condition
          const res = await inner.upsertPrecomputedRaw!(
            id,
            text,
            vector,
            metadata,
            options,
          );
          if (res.ok && id.startsWith('skill:')) seen.add(id);
          return res;
        },
      }),
    };
  }

  async query(
    embedding: IQueryEmbedding,
    k: number,
    options?: {
      signal?: AbortSignal;
      ragFilter?: { namespace?: string; exposition?: string[] };
    },
  ) {
    const log = cds.log('tool-rag');
    const allowedExpositions = options?.ragFilter?.exposition;
    // Strip ragFilter — tools use exposition metadata, not namespace
    const { ragFilter: _unused, ...cleanOpts } = options ?? {};
    // Over-fetch so that (a) exposition post-filtering doesn't starve results and
    // (b) tools crowded out of the top-K by skills can be recovered before the cap.
    // A fixed multiplier is not enough: if every skill outranks the tools, the top
    // k*3 could be all skills and tools would never be fetched. We know exactly how
    // many skills live in this store (the writer tracks them), so add that headroom
    // to GUARANTEE k tools are reachable even when all skills rank first.
    const overFetchK = k * 3 + this.vectorizedSkillIds.size;
    const result = await this.inner.query(embedding, overFetchK, cleanOpts);

    // Give tools their full k budget; cap skills at the top SKILL_RAG_K by score.
    // Input rows are score-descending from the inner store, so slicing keeps the best.
    const capSkills = (rows: RagResult[]) => {
      const tools = rows.filter((r) => !isSkillId(r.metadata.id)).slice(0, k);
      const skills = rows
        .filter((r) => isSkillId(r.metadata.id))
        .slice(0, SKILL_RAG_K);
      return [...tools, ...skills];
    };

    if (result.ok) {
      log.debug('RAG tool search results', {
        k,
        overFetchK,
        totalResults: result.value.length,
        exposition: allowedExpositions ?? 'all',
        results: result.value.map((r) => ({
          id: r.metadata.id,
          score: Math.round(r.score * 1000) / 1000,
          exposition: r.metadata.exposition ?? 'none',
        })),
      });
    }

    if (!result.ok) return result;
    // No role filter (e.g. no exposition passed): still cap skills so they can't
    // crowd tools, but skip exposition post-filtering.
    if (!allowedExpositions) {
      return { ok: true as const, value: capSkills(result.value) };
    }

    // Post-filter by allowed exposition levels. A tool WITHOUT an exposition
    // tag is excluded when a role filter is active — otherwise an un-tagged tool
    // (e.g. a group not mapped in getToolExpositionMap) would bypass role-based
    // filtering and reach every role. Every exposed tool must carry an exposition.
    const allowed = new Set(allowedExpositions);
    const filtered = result.value.filter((r) => {
      // Skills are instruction TEXT, not callable tools. `exposition` gates tool
      // ACCESS; a skill cannot be invoked, so role-filtering it would only hide
      // rules while changing nothing about what the caller may do. The builder
      // upserts them with empty metadata (`upsertRaw('skill:<name>', text, {})`),
      // so without this they would all be dropped and skill injection would
      // silently do nothing. Narrow on purpose: ONLY the `skill:` prefix — an
      // untagged TOOL must still be dropped (the v6.22.0 bypass fix).
      const id = r.metadata.id;
      if (typeof id === 'string' && id.startsWith('skill:')) {
        // A skill is instruction TEXT, not a callable tool — but a WRITE skill
        // (creating-*/activating-*) handed to a read-only caller makes the
        // executor narrate a create it cannot perform (no write tool is granted),
        // fabricating success. So a TAGGED skill is gated by the SAME exposition
        // as the tools it drives; an UNtagged skill still passes (harmless
        // instructions — preserves the default for any future/consumer skill).
        const skillExpo = SKILL_EXPOSITIONS[id.slice('skill:'.length)];
        return !skillExpo || allowed.has(skillExpo);
      }
      return (
        !!r.metadata.exposition && allowed.has(r.metadata.exposition as string)
      );
    });

    if (filtered.length < result.value.length) {
      log.debug('RAG tool search filtered by exposition', {
        before: result.value.length,
        after: filtered.length,
        removed: result.value
          .filter(
            (r) =>
              r.metadata.exposition &&
              !allowed.has(r.metadata.exposition as string),
          )
          .map((r) => r.metadata.id),
      });
    }

    return { ok: true as const, value: capSkills(filtered) };
  }

  async healthCheck() {
    return this.inner.healthCheck();
  }
}

// ---------------------------------------------------------------------------
// Tool → exposition group mapping
// ---------------------------------------------------------------------------
// Each tool belongs to exactly one exposition group (readonly, high, search,
// system, compact). Built once at startup from handler group instances.
// Used to tag tools in RAG metadata for role-based filtering.
// ---------------------------------------------------------------------------

let toolExpositionMap: Map<string, string> | null = null;

function getToolExpositionMap(): Map<string, string> {
  if (toolExpositionMap) return toolExpositionMap;

  const noopCtx: HandlerContext = {
    connection: null as unknown as HandlerContext['connection'],
    logger: loggerAdapter,
  };

  const groups: Array<{
    name: string;
    group: {
      getHandlers(): Array<{
        toolDefinition?: { name: string };
        definition?: { name: string };
      }>;
    };
  }> = [
    { name: 'readonly', group: new ReadOnlyHandlersGroup(noopCtx) },
    { name: 'high', group: new HighLevelHandlersGroup(noopCtx) },
    { name: 'search', group: new SearchHandlersGroup(noopCtx) },
    { name: 'system', group: new SystemHandlersGroup(noopCtx) },
    { name: 'compact', group: new CompactHandlersGroup(noopCtx) },
    // Low-level generic handlers get their own restricted 'low' exposition so
    // they are role-gated (granted only to MCP_Full) instead of falling through
    // as un-tagged tools that bypass ExpositionFilteringRag's role filter.
    { name: 'low', group: new LowLevelHandlersGroup(noopCtx) },
  ];

  toolExpositionMap = new Map();
  for (const { name, group } of groups) {
    for (const h of group.getHandlers()) {
      const toolName = h.toolDefinition?.name ?? h.definition?.name ?? '';
      if (toolName && !toolExpositionMap.has(toolName)) {
        toolExpositionMap.set(toolName, name);
      }
    }
  }
  for (const [t, e] of Object.entries(CLOUD_LOCAL_TOOL_EXPOSITIONS)) {
    toolExpositionMap.set(t, e);
  }

  cds.log('agent-manager').info('Built tool exposition map', {
    total: toolExpositionMap.size,
    readonly: [...toolExpositionMap.values()].filter((v) => v === 'readonly')
      .length,
    high: [...toolExpositionMap.values()].filter((v) => v === 'high').length,
    search: [...toolExpositionMap.values()].filter((v) => v === 'search')
      .length,
    system: [...toolExpositionMap.values()].filter((v) => v === 'system')
      .length,
    compact: [...toolExpositionMap.values()].filter((v) => v === 'compact')
      .length,
    low: [...toolExpositionMap.values()].filter((v) => v === 'low').length,
  });

  return toolExpositionMap;
}

// ---------------------------------------------------------------------------
// Per-request connection override via AsyncLocalStorage
// ---------------------------------------------------------------------------
// SmartAgent tool definitions are shared per destination, but ABAP calls must
// use the current user's per-request connection. callToolHandler reads from ALS
// and refuses to call SAP when no request connection is present.
// ---------------------------------------------------------------------------

type AbapConnectionLike = import('@mcp-abap-adt/interfaces').IAbapConnection;

interface DumpScope {
  principalHash: string;
  resolvedDestination: string;
  effectiveClient: string;
}

// Process-wide buffer for cloud-local dump sections. Must be a singleton: a
// per-call buffer would never hit, defeating the whole point of caching the
// 185K-token formatted payload across GetDumpSection calls. Keys carry only the
// principalHash (never the raw SAP login), so entries are principal-isolated.
// Lazily built: `makeDefaultDumpBuffer` is imported mid-file (below), so a
// top-level `const` would hit its temporal dead zone under CommonJS transpile.
let dumpBufferSingleton: DumpBufferStore | undefined;
function getDumpBuffer(): DumpBufferStore {
  if (!dumpBufferSingleton) {
    dumpBufferSingleton = makeDefaultDumpBuffer(process.env);
  }
  return dumpBufferSingleton;
}

const connectionALS = new AsyncLocalStorage<{
  connection: AbapConnectionLike;
  context: HandlerContext;
  dumpScope?: DumpScope;
}>();

/**
 * Set per-request connection for the current async context.
 * All MCP tool calls in this async scope will use the given connection
 * instead of the shared agent connection. Call before agent.process/streamProcess.
 */
export function setRequestConnection(
  connection: AbapConnectionLike,
  dumpScope?: DumpScope,
): void {
  const context: HandlerContext = { connection, logger: loggerAdapter };
  connectionALS.enterWith({ connection, context, dumpScope });
}

/**
 * Run `fn` with the per-request connection bound for its ENTIRE async subtree.
 *
 * Unlike setRequestConnection (enterWith), `als.run()` keeps the store alive
 * across every await/promise hop inside `fn` — including the SmartAgent pipeline
 * and the MCP tool calls it makes. This is what callToolHandler relies on:
 * without it the store is lost by the time a tool runs and the call fails with
 * "SAP credentials are required". Per-request isolation is preserved (each
 * request gets its own run() scope), which matters on the shared server.
 */
export function runWithRequestConnection<T>(
  connection: AbapConnectionLike,
  fn: () => Promise<T>,
  dumpScope?: DumpScope,
): Promise<T> {
  const context: HandlerContext = { connection, logger: loggerAdapter };
  return connectionALS.run({ connection, context, dumpScope }, fn);
}

import { resolveDestinationSapConfig } from './connections/destinationResolver';
import {
  clearDestinationsCache,
  getAvailableDestinations,
} from './lib/btp-destinations';
import {
  CLOUD_LOCAL_TOOL_EXPOSITIONS,
  CLOUD_LOCAL_TOOLS,
  mergeCloudLocalTools,
} from './lib/cloud-local-tools';
import { type DumpBufferStore, makeDefaultDumpBuffer } from './lib/dump-buffer';
import {
  handleGetDumpSectionCall,
  parseFormattedDumpPayload,
} from './lib/get-dump-section';
import { loggerAdapter } from './lib/logger';
import { SapAiCoreEmbedder } from './lib/sap-ai-core-embedder';
import { SKILL_EXPOSITIONS } from './lib/skill-expositions';
import { buildSkillsPool, logSkillsPool } from './lib/skills-pool';
import { CollectionRegistry } from './rag-collections';

/**
 * Convert inputSchema from HandlerExporter to JSON Schema.
 *
 * HandlerExporter returns Zod raw shapes (Record<string, ZodType>),
 * not JSON Schema. The MCP SDK converts them automatically in listTools,
 * but our embedded MCP path bypasses that conversion.
 */
function toJsonSchema(inputSchema: unknown): Record<string, unknown> {
  if (!inputSchema || typeof inputSchema !== 'object') {
    return { type: 'object', properties: {} };
  }

  // Already JSON Schema (from high-level handlers that define it directly)
  if (
    (inputSchema as Record<string, unknown>).type === 'object' &&
    (inputSchema as Record<string, unknown>).properties
  ) {
    return inputSchema as Record<string, unknown>;
  }

  // Zod raw shape: Record<string, ZodType> — wrap in z.object() and convert
  // Uses Zod v4 built-in toJSONSchema, then strips $schema and additionalProperties
  // which SAP AI Core Orchestration API doesn't expect in tool parameter schemas
  try {
    // biome-ignore lint/suspicious/noExplicitAny: Zod raw shape type varies between handler groups
    const zodObj = z.object(inputSchema as any);
    const result = z.toJSONSchema(zodObj) as Record<string, unknown>;
    delete result.$schema;
    delete result.additionalProperties;
    return result;
  } catch {
    // Fallback: return empty schema
    return { type: 'object', properties: {} };
  }
}

// NOTE: Custom stage handlers (CustomClassifyHandler, CustomToolSelectHandler,
// CustomRagUpsertHandler) and StructuredPipelineDefinition removed in 6.0.0.
// llm-agent now uses DefaultPipeline with consumer-defined RAG stores only.

const agentHandles = new Map<string, SmartAgentHandle>();

/** Set to true after initSmartAgents() completes, regardless of destination success */
let initializationDone = false;

/** Fallback agent without MCP tools — used when no destinations are available */
let llmOnlyHandle: SmartAgentHandle | null = null;

/** Runtime model overrides (null = use config/env default) */
let currentModel: string | null = null;
/** Shared LLM instances (updated on model switch) */
let sharedMainLlm: ReturnType<typeof makeLlm> | null = null;
let sharedClassifierLlm: ReturnType<typeof makeLlm> | null = null;

/** Check if at least one SmartAgent is initialized and ready */
export function isAgentReady(): boolean {
  return initializationDone || agentHandles.size > 0;
}

/** Get the model name currently used by the agent */
export function getCurrentModel(): string {
  return currentModel || getAgentConfig().llm.model;
}

export function getCurrentClassifierModel(): string {
  return process.env.LLM_AGENT_CLASSIFIER_MODEL || getAgentConfig().llm.model;
}

/** Shared metrics instance (survives agent rebuilds) */
const metrics = new InMemoryMetrics();

/** Get agent metrics snapshot */
export function getAgentMetrics() {
  return metrics.snapshot();
}

// ---------------------------------------------------------------------------
// Multi-destination state management
// ---------------------------------------------------------------------------

/** Per-destination pre-built state for fast switching */
export interface DestinationState {
  mcpAdapter: McpClientAdapter | null;
  toolsRag: ExpositionFilteringRag;
  toolCount: number;
  status: 'pending' | 'ready' | 'vectorizing' | 'error' | 'unreachable';
  error?: string;
  /** BTP destination ProxyType ('OnPremise' | 'Internet'), when known. */
  proxyType?: string;
  /**
   * True when this destination requires the caller's own SAP credentials
   * (on-premise / NoAuthentication). The chat UI uses this to prompt for
   * login/password on connect. Cloud destinations (JWT) are false.
   */
  requiresCredentials?: boolean;
}

/**
 * Whether a destination requires the caller's own SAP credentials.
 * On-premise (Cloud Connector) and NoAuthentication destinations do; cloud
 * destinations with their own auth (JWT via OAuth2*) do not. Mirrors the
 * fail-closed rule in srv/lib/request-connection.ts.
 */
export function destinationRequiresCredentials(
  proxyType?: string,
  authentication?: string,
): boolean {
  return (
    (proxyType ?? '').toLowerCase() === 'onpremise' ||
    authentication === 'NoAuthentication'
  );
}

/** Map of destination name → pre-built state */
const destinationStates = new Map<string, DestinationState>();

/**
 * In-flight `initDestination` promises, keyed by destination name.
 * Guarantees at most ONE concurrent vectorization per destination: every
 * caller (startup warm, background loop, /destinations/refresh, the retry
 * timer, and the lazy path in getSmartAgent) goes through
 * `ensureDestinationInit`, so a refresh/retry racing a first request cannot
 * double-vectorize the same destination.
 */
const destinationInits = new Map<string, Promise<DestinationState>>();

// ---------------------------------------------------------------------------
// System-to-destination mapping (e.g., "DEV.100" → "S4HANA_DEV")
// ---------------------------------------------------------------------------
// Configured via DESTINATION_MAPPING env var: "DEV.100=S4HANA_DEV,QAS.600=S4HANA_QAS"

const systemDestinationMap = new Map<string, string>();

/** Parse DESTINATION_MAPPING env var at startup */
function initDestinationMapping(): void {
  const raw = process.env.DESTINATION_MAPPING || '';
  if (!raw) return;
  const log = cds.log('agent-manager');
  for (const pair of raw.split(',')) {
    const [system, dest] = pair.split('=').map((s) => s.trim());
    if (system && dest) {
      systemDestinationMap.set(system, dest);
    }
  }
  if (systemDestinationMap.size > 0) {
    log.info('Destination mapping loaded', {
      mappings: Object.fromEntries(systemDestinationMap),
    });
  }
}

/**
 * Resolve a SAP system code (e.g., "DEV.100") to a BTP destination name.
 * Returns the destination name if found and active, or an error.
 */
export function resolveSystemDestination(systemCode: string): {
  ok: boolean;
  destination?: string;
  error?: string;
} {
  const dest = systemDestinationMap.get(systemCode);
  if (!dest) {
    return {
      ok: false,
      error: `No destination mapping for system "${systemCode}". Configure DESTINATION_MAPPING env var.`,
    };
  }

  // Resolving a system code is just a NAME mapping — it must NOT require the
  // destination to be vectorized. With no blocking startup init, a cold-start
  // caller may resolve before warmup finishes; absent / pending / vectorizing
  // are all resolvable. Fail only on a terminal state (unreachable / error).
  const state = destinationStates.get(dest);
  if (state?.status === 'unreachable' || state?.status === 'error') {
    return {
      ok: false,
      error: `Destination "${dest}" (mapped from "${systemCode}") is ${state.status}: ${state.error || 'unavailable'}`,
    };
  }

  // Kick off warmup (fire-and-forget) so a resolve also starts vectorization;
  // the subsequent getSmartAgent call then waits on the same shared init.
  if (!agentHandles.has(dest)) {
    ensureDestinationInit(dest).catch(() => undefined);
  }

  return { ok: true, destination: dest };
}

/** Get all configured system-to-destination mappings */
export function getDestinationMappings(): Record<string, string> {
  return Object.fromEntries(systemDestinationMap);
}

/** Last-used destination per session (for detecting switches in openai-handler) */
const lastDestinationBySession = new Map<string, string>();

/**
 * Per-session conversation topic — the classified ragText from the previous request.
 * Used by CustomToolSelectHandler to enrich short follow-up messages with topic context,
 * so RAG tool selection stays relevant without extra LLM token cost.
 * Example: "create hello world class" persists → next message "ZCL_DEMO_HELLO_AI1"
 * gets enriched → CreateClass found by RAG.
 */
const sessionTopicMap = new Map<string, string>();

/** Get last-used destination for a session, or config default */
export function getCurrentDestination(sessionId?: string): string {
  if (sessionId) {
    return (
      lastDestinationBySession.get(sessionId) ||
      getAgentConfig().mcp.destination
    );
  }
  return getAgentConfig().mcp.destination;
}

/** Clear session topic (call on destination switch alongside clearSession) */
export function clearSessionTopic(sessionId: string): void {
  sessionTopicMap.delete(sessionId);
}

/** Track which destination was used for a session */
export function setSessionDestination(
  sessionId: string,
  destination: string,
): void {
  lastDestinationBySession.set(sessionId, destination);
}

/** Get all destination states for API/UI consumption */
export function getDestinationStates(): Array<{
  name: string;
  status: string;
  toolCount: number;
  error?: string;
  proxyType?: string;
  requiresCredentials?: boolean;
}> {
  return [...destinationStates.entries()].map(([name, state]) => ({
    name,
    status: state.status,
    toolCount: state.toolCount,
    error: state.error,
    proxyType: state.proxyType,
    requiresCredentials: state.requiresCredentials,
  }));
}

/**
 * Refresh unreachable destinations on demand (called from API endpoint).
 * Re-runs initDestination for all unreachable destinations.
 * Returns updated destination states.
 */
export async function refreshDestinations(): Promise<
  ReturnType<typeof getDestinationStates>
> {
  const log = cds.log('agent-manager');

  // Force re-fetch from BTP (clear 5-min cache)
  clearDestinationsCache();
  const available = await getAvailableDestinations();

  // New destinations not yet in state map
  const newDests = available.filter((d) => !destinationStates.has(d.name));

  // Already known unreachable destinations
  const unreachable = [...destinationStates.entries()]
    .filter(([, s]) => s.status === 'unreachable')
    .map(([name]) => name);

  log.info('Manual destination refresh triggered', {
    fetched: available.map((d) => d.name),
    new: newDests.map((d) => d.name),
    unreachable,
  });

  for (const d of newDests) {
    await ensureDestinationInit(d.name);
  }

  for (const name of unreachable) {
    await ensureDestinationInit(name);
    const state = destinationStates.get(name);
    if (state?.status === 'ready') {
      log.info('Destination recovered after manual refresh', {
        destination: name,
        toolCount: state.toolCount,
      });
    }
  }

  return getDestinationStates();
}

// ---------------------------------------------------------------------------
// Shared embedder + RAG stores (survive destination switches)
// ---------------------------------------------------------------------------

let sharedEmbedderBreaker: CircuitBreaker | null = null;
let sharedEmbedder: CircuitBreakerEmbedder | null = null;

// ---------------------------------------------------------------------------
// Collection Registry (singleton — manages dynamic RAG collections)
// ---------------------------------------------------------------------------

let collectionRegistryInstance: CollectionRegistry | null = null;

/** Get or create the shared CollectionRegistry. */
export function getCollectionRegistry(): CollectionRegistry {
  if (!collectionRegistryInstance) {
    const embedding = getOrCreateEmbedder(getAgentConfig().llm.resourceGroup);
    collectionRegistryInstance = new CollectionRegistry({
      storagePath: process.env.RAG_STORAGE_PATH || undefined,
      embedder: embedding?.embedder ?? null,
      breaker: embedding?.breaker ?? null,
    });
  }
  return collectionRegistryInstance;
}

/** Get or create shared embedder (singleton) */
function getOrCreateEmbedder(resourceGroup?: string): {
  embedder: CircuitBreakerEmbedder;
  breaker: CircuitBreaker;
} | null {
  const config = getAgentConfig();
  if (config.agent.ragType === 'in-memory') return null;

  if (!sharedEmbedder) {
    const embeddingModel =
      process.env.LLM_AGENT_EMBEDDING_MODEL || 'text-embedding-3-small';
    sharedEmbedderBreaker = new CircuitBreaker({
      failureThreshold: 30,
      recoveryWindowMs: 60_000,
    });

    // Create embedder based on LLM provider
    let rawEmbedder: SapAiCoreEmbedder | OpenAiEmbedder;
    if (config.llm.provider === 'sap-ai-sdk') {
      rawEmbedder = new SapAiCoreEmbedder({
        model: embeddingModel,
        resourceGroup,
      });
    } else {
      // OpenAI-compatible embedder for openai/anthropic/deepseek providers
      rawEmbedder = new OpenAiEmbedder({
        apiKey: config.llm.apiKey || '',
        baseURL: config.llm.baseUrl,
        model: embeddingModel,
      });
    }

    sharedEmbedder = new CircuitBreakerEmbedder(
      rawEmbedder,
      sharedEmbedderBreaker,
    );
  }

  return {
    embedder: sharedEmbedder,
    breaker: sharedEmbedderBreaker as NonNullable<typeof sharedEmbedderBreaker>,
  };
}

/** Create a tools RAG store (one per destination), wrapped to ignore ragFilter */
async function createToolsRagStore(
  resourceGroup?: string,
): Promise<ExpositionFilteringRag> {
  const embedding = getOrCreateEmbedder(resourceGroup);
  if (!embedding) return new ExpositionFilteringRag(new InMemoryRag());

  const config = getAgentConfig();
  const helperLlm = await makeLlm(
    {
      provider: config.llm.provider,
      apiKey: config.llm.apiKey || 'sap-ai-sdk-managed',
      baseURL: config.llm.baseUrl,
      model: process.env.LLM_AGENT_CLASSIFIER_MODEL || config.llm.model,
      resourceGroup: config.llm.resourceGroup,
    },
    0.1,
  );

  // Enrichment is handled in vectorizeToolDocs() — either from cache or via
  // IntentEnricher for uncached tools. VectorRag always uses NoopDocumentEnricher
  // since enriched text is supplied pre-built at upsert time.
  const toolsVectorRag = new VectorRag(embedding.embedder, {
    vectorWeight: 0.7,
    keywordWeight: 0.3,
    queryPreprocessors: [new TranslatePreprocessor(helperLlm)],
    documentEnrichers: [new NoopDocumentEnricher()],
  });
  const fallback = new FallbackRag(
    toolsVectorRag,
    new InMemoryRag(),
    embedding.breaker,
  );
  return new ExpositionFilteringRag(fallback);
}

// ---------------------------------------------------------------------------
// Tool vectorization (extracted for reuse across destinations)
// ---------------------------------------------------------------------------

/** Minimal tool shape needed to assemble a tool-doc (from listTools OR HandlerExporter). */
export type ToolDocInput = {
  name: string;
  description?: string;
  inputSchema?: unknown;
};
type ToolDocBasicEntry = {
  name: string;
  description: string;
  paramNames: string;
  text: string;
};

/**
 * Assemble the FINAL tool-doc corpus text — destination-independent and
 * deterministic for CACHED tools. This is the single source of truth for the
 * embedded text, shared by runtime vectorization and the build-time embedding
 * generator (`tools/generate-tool-embeddings.ts`). Byte-identical to the former
 * inline logic: base "Tool/Description/Parameters" text → `tool-intents.json`
 * enriched text when present → CRUD/"Workflow:" hints appended.
 *
 * Params are read via `toJsonSchema` so a raw Zod `inputSchema` (HandlerExporter)
 * yields the same names as an already-JSON-Schema `inputSchema` (listTools).
 *
 * Returns `entries` (final text, with hints) and `uncached` (base entries, NO
 * hints — the LLM enrich step consumes these and OVERWRITES the entry text,
 * preserving the existing hints-loss quirk for uncached tools). `cached` flags
 * whether the tool had an enriched intent (so the generator can fail-fast).
 */
export function buildToolDocs(tools: ToolDocInput[]): {
  entries: { name: string; text: string; cached: boolean }[];
  uncached: ToolDocBasicEntry[];
} {
  const basicEntries: ToolDocBasicEntry[] = tools.map((t) => {
    const paramNames = Object.keys(
      (toJsonSchema(t.inputSchema).properties as
        | Record<string, unknown>
        | undefined) ?? {},
    ).join(', ');
    return {
      name: t.name,
      description: t.description || '',
      paramNames,
      text: [
        `Tool: ${t.name}`,
        `Description: ${t.description}`,
        paramNames ? `Parameters: ${paramNames}` : '',
      ]
        .filter(Boolean)
        .join('\n'),
    };
  });

  // Pre-generated intent cache: cached (enriched) tools are deterministic; the
  // rest are collected as uncached for the LLM enrich step downstream.
  const cache = getToolIntentCache();
  const uncached: ToolDocBasicEntry[] = [];
  const entries = basicEntries.map((t) => {
    const cached = cache?.[t.name];
    if (cached?.enriched?.includes('\nIntent:')) {
      return { name: t.name, text: cached.enriched, cached: true };
    }
    uncached.push(t);
    return { name: t.name, text: t.text, cached: false };
  });

  // Enrich CRUD tool descriptions with related operation context (BM25/vector
  // recall). Appended to both cached and uncached text.
  const toolNameSet = new Set(basicEntries.map((t) => t.name));
  for (const t of entries) {
    const m = t.name.match(/^(Create|Update|Read)(.+)$/);
    if (!m) continue;
    const [, verb, object] = m;
    const objWords = object.replace(/([a-z])([A-Z])/g, '$1 $2').toLowerCase();
    const hints: string[] = [];
    if (verb === 'Create') {
      if (toolNameSet.has(`Update${object}`))
        hints.push(
          `After creating, use Update${object} (update ${objWords}) to add source code/content.`,
        );
      if (toolNameSet.has(`Activate${object}`))
        hints.push(
          `Use Activate${object} (activate ${objWords}) to activate after creation.`,
        );
    } else if (verb === 'Update') {
      if (toolNameSet.has(`Create${object}`))
        hints.push(
          `Also used after create ${objWords} (Create${object}) to add implementation.`,
        );
    } else if (verb === 'Read') {
      if (toolNameSet.has(`Update${object}`))
        hints.push(
          `Use to inspect current ${objWords} before update (Update${object}), or verify after create (Create${object}).`,
        );
    }
    if (hints.length > 0) {
      t.text += `\nWorkflow: ${hints.join(' ')}`;
    }
  }

  return { entries, uncached };
}

/**
 * Vectorize an explicit tool list into a RAG store. Source-agnostic: the tools
 * come directly from `HandlerExporter` (the shared, destination-free corpus).
 * Assembles docs via `buildToolDocs`, LLM-enriches uncached tools, embeds/upserts.
 */
async function vectorizeToolDocs(
  tools: ToolDocInput[],
  toolsStore: ExpositionFilteringRag,
  embedderBreaker: CircuitBreaker | null,
  onlyNames?: Set<string>,
): Promise<{ ok: number; failed: number; total: number }> {
  const log = cds.log('agent-manager');

  const maxRetries = 3;
  const throttleMs = 50;

  // Assemble tool-doc corpus (base text + cache enrich + Workflow hints).
  const cache = getToolIntentCache();
  const { entries: toolEntries, uncached: uncachedTools } =
    buildToolDocs(tools);

  // Enrich uncached tools via LLM (only runs for tools missing from cache)
  if (uncachedTools.length > 0 && cache) {
    const config = getAgentConfig();
    const helperLlm = await makeLlm(
      {
        provider: config.llm.provider,
        apiKey: config.llm.apiKey || 'sap-ai-sdk-managed',
        baseURL: config.llm.baseUrl,
        model: process.env.LLM_AGENT_CLASSIFIER_MODEL || config.llm.model,
        resourceGroup: config.llm.resourceGroup,
      },
      0.1,
    );
    const enricher = new IntentEnricher(helperLlm);
    log.info('Enriching uncached tools via LLM', {
      count: uncachedTools.length,
      names: uncachedTools.map((t) => t.name).slice(0, 10),
    });
    for (const t of uncachedTools) {
      const res = await enricher.enrich(t.text);
      if (res.ok && res.value.includes('\nIntent:')) {
        const entry = toolEntries.find((e) => e.name === t.name);
        if (entry) entry.text = res.value;
      }
    }
  }

  // Docs (and their Workflow hints) are built from the FULL `tools` set so
  // sibling-derived hints are correct; when `onlyNames` is given (partial
  // bundle supplement) we UPSERT only that subset — the canonical full-set text.
  let pending = onlyNames
    ? toolEntries.filter((t) => onlyNames.has(t.name))
    : toolEntries;
  const totalToProcess = pending.length;
  let totalOk = 0;

  for (
    let attempt = 0;
    attempt <= maxRetries && pending.length > 0;
    attempt++
  ) {
    if (attempt > 0) {
      const waitMs = 65_000;
      log.info(
        `Vectorization retry ${attempt}/${maxRetries}: waiting ${waitMs}ms, ${pending.length} tools remaining`,
      );
      await new Promise((r) => setTimeout(r, waitMs));
      embedderBreaker?.recordSuccess();
    }

    const failed: typeof pending = [];
    for (const t of pending) {
      const expo = getToolExpositionMap().get(t.name);
      const res = await toolsStore.upsert(t.text, {
        id: `tool:${t.name}`,
        ...(expo ? { exposition: expo } : {}),
      });
      if (res.ok) {
        totalOk++;
      } else {
        failed.push(t);
      }
      if (throttleMs > 0) {
        await new Promise((r) => setTimeout(r, throttleMs));
      }
    }
    pending = failed;

    if (pending.length > 0) {
      log.warn(
        `Vectorization attempt ${attempt}: ${failed.length} failed, ${totalOk} succeeded`,
        { embedderBreakerState: embedderBreaker?.state ?? 'n/a' },
      );
    }
  }

  if (pending.length > 0) {
    log.error('Tool vectorization incomplete', {
      failedCount: pending.length,
      failedTools: pending.map((t) => t.name).slice(0, 20),
      totalTools: tools.length,
      successCount: totalOk,
    });
  }

  log.info('Vectorized MCP tools', {
    toolCount: tools.length,
    upsertOk: totalOk,
    embedderBreakerState: embedderBreaker?.state ?? 'n/a',
  });

  return { ok: totalOk, failed: pending.length, total: totalToProcess };
}

// ---------------------------------------------------------------------------
// Shared tool corpus (destination-independent, vectorized ONCE)
// ---------------------------------------------------------------------------
// The tool set + intent text is identical for every destination (tools come
// from HandlerExporter, not from a per-destination system), so the tool-RAG is
// built ONCE and shared by all destination agents instead of re-vectorized N
// times. Read-only after build → safe to share across agents.

/**
 * HandlerExporter include-config — the single source of truth shared by the RAG
 * tool list (`listToolDefsFromExporter`) and the callable MCP adapter
 * (`buildEmbeddedMcpAdapter`) so they never diverge.
 *
 * The COMPACT group exposes generic low-level handlers (`HandlerCreate`,
 * `HandlerActivate`, `HandlerLock`, `HandlerTransportCreate`, …) ALONGSIDE the
 * high-level named tools (`CreatePackage`, `CreateClass`, …). Exposing both lets
 * the agent pick a generic low-level handler for a "create" when it should use
 * the high-level tool. So compact/low-level are now OPT-IN via env, OFF by
 * default — enable explicitly at deploy only:
 *   LLM_AGENT_INCLUDE_COMPACT=true    (generic compact/low-level handlers)
 *   LLM_AGENT_INCLUDE_LOW_LEVEL=true  (the low handler group)
 */
export function getHandlerExporterConfig(env: NodeJS.ProcessEnv = process.env) {
  return {
    includeReadOnly: true,
    includeHighLevel: true,
    includeLowLevel: env.LLM_AGENT_INCLUDE_LOW_LEVEL === 'true',
    includeCompact: env.LLM_AGENT_INCLUDE_COMPACT === 'true',
    includeSystem: true,
    includeSearch: true,
    logger: loggerAdapter,
  };
}

/** Static, destination-free tool list from HandlerExporter (same config as buildEmbeddedMcpAdapter). */
function listToolDefsFromExporter(): ToolDocInput[] {
  const exporter = new HandlerExporter(getHandlerExporterConfig());
  const coreTools = exporter.getHandlerEntries().map((e) => ({
    name: e.toolDefinition.name,
    description: e.toolDefinition.description,
    inputSchema: e.toolDefinition.inputSchema,
  }));
  return mergeCloudLocalTools(coreTools);
}

/** One shared-corpus doc: the upsert `id`, final `text`, exposition tag, cached flag. */
export type SharedCorpusDoc = {
  id: string;
  name: string;
  text: string;
  exposition?: string;
  cached: boolean;
};

/**
 * The canonical shared tool corpus (deterministic for cached tools) — the single
 * source of truth for both the build-time embedding generator and the runtime
 * bundle loader's per-entry text match. Built from `HandlerExporter` (no
 * destination) via `buildToolDocs`; `cached` marks tools with a pre-generated
 * intent (uncached tools are LLM-enriched at runtime, not part of the bundle).
 */
export function getSharedCorpusDocs(): SharedCorpusDoc[] {
  const { entries } = buildToolDocs(listToolDefsFromExporter());
  const expoMap = getToolExpositionMap();
  return entries.map((e) => ({
    id: `tool:${e.name}`,
    name: e.name,
    text: e.text,
    exposition: expoMap.get(e.name),
    cached: e.cached,
  }));
}

// ---------------------------------------------------------------------------
// Build-time embedding bundle (srv/tool-embeddings.json)
// ---------------------------------------------------------------------------
// Precomputed embeddings for the full corpus, generated by
// tools/generate-tool-embeddings.ts. Loaded at startup via upsertPrecomputedRaw
// with ZERO embedding calls on the happy path (the vector space is gated by a
// config-only fingerprint; each vector by per-entry text identity).

type EmbedderFingerprint = {
  provider: string;
  embeddingModel: string;
  baseURL?: string;
  resourceGroup?: string;
};
type ToolEmbeddingBundle = {
  header: {
    embedderFingerprint: EmbedderFingerprint;
    embeddingDim: number;
    coreVersion?: string;
    generatedAt?: string;
    canary?: { text: string; vector: number[] };
  };
  entries: {
    id: string;
    name: string;
    text: string;
    vector: number[];
    exposition?: string;
  }[];
};

/** Runtime embedder identity — read from config, NO embedding call. */
export function runtimeEmbedderFingerprint(
  config: AgentConfig = getAgentConfig(),
): EmbedderFingerprint {
  const provider = config.llm.provider;
  const embeddingModel =
    process.env.LLM_AGENT_EMBEDDING_MODEL || 'text-embedding-3-small';
  return provider === 'sap-ai-sdk'
    ? {
        provider,
        embeddingModel,
        resourceGroup: config.llm.resourceGroup || 'default',
      }
    : { provider, embeddingModel, baseURL: config.llm.baseUrl };
}

/** Fingerprint equality — provider + model + endpoint identity (no dim). */
export function fingerprintMatches(
  bundle: EmbedderFingerprint,
  runtime: EmbedderFingerprint,
): boolean {
  return (
    bundle.provider === runtime.provider &&
    bundle.embeddingModel === runtime.embeddingModel &&
    (bundle.baseURL ?? '') === (runtime.baseURL ?? '') &&
    (bundle.resourceGroup ?? '') === (runtime.resourceGroup ?? '')
  );
}

/**
 * Pure plan (no embedding, no store writes — unit-testable): given a bundle, the
 * runtime corpus docs, and the runtime fingerprint, decide what loads from the
 * bundle (fingerprint match + per-entry text identity) vs what must be
 * vectorized at runtime (missing / changed text). A fingerprint mismatch
 * invalidates the WHOLE bundle.
 */
export function planBundleLoad(
  bundle: ToolEmbeddingBundle | null,
  runtimeDocs: SharedCorpusDoc[],
  runtime: EmbedderFingerprint,
): {
  usable: boolean;
  toLoad: { id: string; text: string; vector: number[]; exposition?: string }[];
  supplementNames: string[];
} {
  if (
    !bundle ||
    !fingerprintMatches(bundle.header.embedderFingerprint, runtime)
  ) {
    return {
      usable: false,
      toLoad: [],
      supplementNames: runtimeDocs.map((d) => d.name),
    };
  }
  const byId = new Map(bundle.entries.map((e) => [e.id, e]));
  const toLoad: {
    id: string;
    text: string;
    vector: number[];
    exposition?: string;
  }[] = [];
  const supplementNames: string[] = [];
  for (const d of runtimeDocs) {
    const be = byId.get(d.id);
    if (be && be.text === d.text) {
      toLoad.push({
        id: d.id,
        text: d.text,
        vector: be.vector,
        exposition: d.exposition,
      });
    } else {
      supplementNames.push(d.name);
    }
  }
  return { usable: true, toLoad, supplementNames };
}

function loadToolEmbeddingBundle(): ToolEmbeddingBundle | null {
  const p = path.resolve(__dirname, 'tool-embeddings.json');
  try {
    if (!fs.existsSync(p)) return null;
    return JSON.parse(fs.readFileSync(p, 'utf-8')) as ToolEmbeddingBundle;
  } catch {
    return null;
  }
}

let sharedToolsRag: ExpositionFilteringRag | null = null;
let sharedToolsInit: Promise<ExpositionFilteringRag> | null = null;
let sharedToolCount = 0;

/**
 * Build (once) and return the shared tool-RAG store. Global single-flight:
 * concurrent callers share ONE build; on success `sharedToolsRag` is cached and
 * reused; on failure the in-flight promise is cleared so a later call retries.
 * Vector mode loads the build-time bundle (zero embedding on the happy path)
 * and supplements only missing/changed tools; in-memory mode populates text-only.
 */
function ensureSharedToolsVectorized(): Promise<ExpositionFilteringRag> {
  if (sharedToolsRag) return Promise.resolve(sharedToolsRag);
  if (sharedToolsInit) return sharedToolsInit;
  const log = cds.log('agent-manager');
  sharedToolsInit = (async () => {
    const config = getAgentConfig();
    const store = await createToolsRagStore(config.llm.resourceGroup);
    const embedding = getOrCreateEmbedder(config.llm.resourceGroup);

    // In-memory mode (no embedder): no vectors — populate text-only via the
    // runtime path (which still LLM-enriches uncached tools). Bundle is vectors-
    // only, so it does not apply here.
    if (!embedding) {
      const result = await vectorizeToolDocs(
        listToolDefsFromExporter(),
        store,
        null,
      );
      sharedToolCount = result.ok;
      sharedToolsRag = store;
      log.info('Shared tool corpus ready (in-memory, keyword-only)', {
        toolCount: result.ok,
      });
      return store;
    }

    // Vector mode: bundle fast path (zero embedding when fingerprint + all
    // per-entry texts match).
    const runtimeDocs = getSharedCorpusDocs();
    const plan = planBundleLoad(
      loadToolEmbeddingBundle(),
      runtimeDocs,
      runtimeEmbedderFingerprint(config),
    );

    if (plan.usable) {
      const writer = store.writer();
      for (const e of plan.toLoad) {
        await writer?.upsertPrecomputedRaw?.(
          e.id,
          e.text,
          e.vector,
          e.exposition ? { exposition: e.exposition } : {},
        );
      }
      // Supplement missing/changed tools. Build docs from the FULL tool set so
      // Workflow hints (sibling-derived) are correct, but UPSERT only the
      // supplement subset — otherwise a supplemented tool's text would lose
      // hints for siblings that live in the bundle and diverge from the
      // canonical runtime text that triggered the supplement.
      if (plan.supplementNames.length > 0) {
        await vectorizeToolDocs(
          listToolDefsFromExporter(),
          store,
          embedding.breaker,
          new Set(plan.supplementNames),
        );
      }
      sharedToolCount = plan.toLoad.length + plan.supplementNames.length;
      sharedToolsRag = store;
      log.info('Shared tool corpus ready (bundle)', {
        loaded: plan.toLoad.length,
        supplemented: plan.supplementNames.length,
      });
      return store;
    }

    // No/invalid bundle → full runtime vectorization.
    const result = await vectorizeToolDocs(
      listToolDefsFromExporter(),
      store,
      embedding.breaker,
    );
    sharedToolCount = result.ok;
    sharedToolsRag = store;
    log.info('Shared tool corpus ready (runtime vectorization)', {
      toolCount: result.ok,
      bundle: 'absent-or-mismatch',
    });
    return store;
  })();
  sharedToolsInit.catch(() => {
    // Allow a retry on the next call after a failed build.
    sharedToolsInit = null;
  });
  return sharedToolsInit;
}

// ---------------------------------------------------------------------------
// Per-destination initialization
// ---------------------------------------------------------------------------

/**
 * Initialize a single destination: build MCP adapter, vectorize tools, build SmartAgent.
 * Updates destinationStates map and agentHandles map.
 */
async function initDestination(
  destinationName: string,
): Promise<DestinationState> {
  const log = cds.log('agent-manager');
  const config = getAgentConfig();

  log.info('Initializing destination', { destination: destinationName });

  // Carry destination metadata (proxyType/auth) so the UI can prompt for SAP
  // credentials on connect for on-premise destinations. Preserve any value
  // already set by the pre-populate pass.
  const prev = destinationStates.get(destinationName);
  let proxyType = prev?.proxyType;
  let requiresCredentials = prev?.requiresCredentials;
  if (proxyType === undefined) {
    try {
      const meta = (await getAvailableDestinations()).find(
        (d) => d.name === destinationName,
      );
      if (meta) {
        proxyType = meta.proxyType;
        requiresCredentials = destinationRequiresCredentials(
          meta.proxyType,
          meta.authentication,
        );
      }
    } catch {
      // Non-fatal: UI falls back to the 401 SAP_CREDENTIALS_REQUIRED prompt.
    }
  }

  // Shared tool corpus — vectorized ONCE and reused by every destination
  // (destination-independent). This replaces the former per-destination
  // vectorization; the first caller triggers the build, the rest share it.
  const sharedRag = await ensureSharedToolsVectorized();

  const state: DestinationState = {
    mcpAdapter: null,
    toolsRag: sharedRag,
    toolCount: sharedToolCount,
    status: 'vectorizing',
    proxyType,
    requiresCredentials,
  };
  destinationStates.set(destinationName, state);

  try {
    state.mcpAdapter = await buildEmbeddedMcpAdapter(destinationName);

    // Build a full SmartAgent for this destination, referencing the SHARED
    // tool RAG (no per-destination re-vectorization).
    const handle = await buildAgentForDestination(
      state.mcpAdapter,
      sharedRag,
      config,
    );
    agentHandles.set(destinationName, handle);
    state.status = 'ready';
    log.info('Destination ready', {
      destination: destinationName,
      toolCount: state.toolCount,
    });
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    state.error = errorMsg;
    // Distinguish unreachable (probe failed) from other init errors
    if (errorMsg.includes('unreachable')) {
      state.status = 'unreachable';
      log.warn('Destination unreachable, skipping', {
        destination: destinationName,
        error: errorMsg,
      });
    } else {
      state.status = 'error';
      log.error('Destination initialization failed', {
        destination: destinationName,
        error: errorMsg,
      });
    }
  }

  return state;
}

/**
 * Init a destination through the in-flight dedup map: if an init for `name` is
 * already running, return that promise; otherwise start one and register it,
 * clearing the entry when it settles. Callers that only want a READY handle
 * (getSmartAgent) must check `agentHandles` first — this always (re)runs
 * `initDestination` when nothing is in flight, which is what refresh/retry want.
 */
function ensureDestinationInit(name: string): Promise<DestinationState> {
  const existing = destinationInits.get(name);
  if (existing) return existing;
  const p = initDestination(name).finally(() => {
    destinationInits.delete(name);
  });
  destinationInits.set(name, p);
  return p;
}

/**
 * Initialize remaining destinations in background (after primary is ready).
 * Fetches available SAP destinations from BTP Destination Service and
 * vectorizes each one's MCP tools into a separate RAG store.
 */
async function initBackgroundDestinations(): Promise<void> {
  const log = cds.log('agent-manager');

  try {
    const destinations = await getAvailableDestinations();
    // No privileged primary: warm ALL destinations. The configured
    // LLM_AGENT_MCP_DESTINATION is only an optional "warm this first" hint —
    // it is initialized like any other, just earlier in the queue.
    const hint = getAgentConfig().mcp.destination;
    const ordered = hint
      ? [
          ...destinations.filter((d) => d.name === hint),
          ...destinations.filter((d) => d.name !== hint),
        ]
      : destinations;

    if (ordered.length === 0) {
      log.info('No destinations to initialize');
      return;
    }

    log.info('Starting background destination warmup', {
      destinations: ordered.map((d) => d.name),
      warmFirst: hint || null,
    });

    // Register all destinations as 'pending' immediately so UI sees the full list
    for (const dest of ordered) {
      if (!destinationStates.has(dest.name)) {
        destinationStates.set(dest.name, {
          mcpAdapter: null,
          toolsRag: new ExpositionFilteringRag(new InMemoryRag()),
          toolCount: 0,
          status: 'pending',
          proxyType: dest.proxyType,
          requiresCredentials: destinationRequiresCredentials(
            dest.proxyType,
            dest.authentication,
          ),
        });
      }
    }

    // Sequential: each destination does embedding calls, avoid overwhelming the
    // embedding API. (No destination-level concurrency limit today; a later
    // change can add LLM_AGENT_DEST_INIT_CONCURRENCY if this proves too slow.)
    for (const dest of ordered) {
      const state = destinationStates.get(dest.name);
      if (state?.status === 'ready') continue;
      await ensureDestinationInit(dest.name);
    }

    const states = [...destinationStates.values()];
    log.info('Background destination initialization complete', {
      total: destinationStates.size,
      ready: states.filter((s) => s.status === 'ready').length,
      unreachable: states.filter((s) => s.status === 'unreachable').length,
      errors: states.filter((s) => s.status === 'error').length,
    });

    // Schedule periodic retry for unreachable destinations
    scheduleUnreachableRetry();
  } catch (err) {
    log.warn('Background destination initialization failed', {
      error: err instanceof Error ? err.message : String(err),
    });
  }
}

/** Periodically retry unreachable destinations (every 5 min) */
const UNREACHABLE_RETRY_INTERVAL_MS = 5 * 60 * 1000;
let unreachableRetryTimer: ReturnType<typeof setInterval> | null = null;

function scheduleUnreachableRetry(): void {
  if (unreachableRetryTimer) return;
  const log = cds.log('agent-manager');

  unreachableRetryTimer = setInterval(async () => {
    const unreachable = [...destinationStates.entries()].filter(
      ([, s]) => s.status === 'unreachable',
    );
    if (unreachable.length === 0) {
      // All destinations reachable — stop retrying
      if (unreachableRetryTimer) {
        clearInterval(unreachableRetryTimer);
        unreachableRetryTimer = null;
      }
      return;
    }

    log.info('Retrying unreachable destinations', {
      destinations: unreachable.map(([name]) => name),
    });

    for (const [name] of unreachable) {
      await ensureDestinationInit(name);
      const state = destinationStates.get(name);
      if (state?.status === 'ready') {
        log.info('Previously unreachable destination is now ready', {
          destination: name,
          toolCount: state.toolCount,
        });
      }
    }
  }, UNREACHABLE_RETRY_INTERVAL_MS);
}

/**
 * Build embedded MCP client (in-process, no HTTP).
 *
 * Uses HandlerExporter to get tool definitions and handlers directly,
 * then wraps them in MCPClientWrapper with `transport: 'embedded'`.
 * Connection is resolved from BTP Destination and injected as handler context.
 */
async function buildEmbeddedMcpAdapter(
  destinationName: string,
): Promise<McpClientAdapter> {
  const log = cds.log('agent-manager');

  // Resolve destination metadata for proxy type/system type only. Do not probe
  // or connect here: on-premise destinations must not use a destination service
  // user at startup. Real ABAP credentials are supplied per request.
  await resolveDestinationSapConfig(destinationName);

  setSystemContext({});

  // Load ALL tool handlers — role-based filtering happens at RAG query time
  // via ExpositionFilteringRag (post-filter by exposition metadata).
  // Low-level handlers excluded: they duplicate high-level with finer granularity.
  const exporter = new HandlerExporter(getHandlerExporterConfig());

  const entries = exporter.getHandlerEntries();

  // Handler context with a placeholder connection. Every actual tool call below
  // must receive a per-request connection via connectionALS.
  const context: HandlerContext = {
    connection:
      null as unknown as import('@mcp-abap-adt/interfaces').IAbapConnection,
    logger: loggerAdapter,
  };

  // Inject real connection into handler groups so closure-based handlers (handler.length === 1)
  // use our connection instead of dummyContext (connection: null).
  // HandlerExporter creates groups with dummyContext; BaseMcpServer.registerHandlers() fixes this
  // by setting group.context before calling, but we bypass that — so we do it here.
  // biome-ignore lint/suspicious/noExplicitAny: accessing private handlerGroups field
  const handlerGroups = (exporter as any).handlerGroups as Array<{
    context: HandlerContext;
  }>;
  if (handlerGroups) {
    for (const group of handlerGroups) {
      group.context = context;
    }
  }

  // Build handler map (handlers now use updated group.context via closure)
  const handlerMap = new Map(
    entries.map((e) => [e.toolDefinition.name, e.handler]),
  );

  log.info('Building embedded MCP client', {
    destination: destinationName,
    connectionType: 'per-request',
    toolCount: entries.length,
    tools: exporter.getToolNames(),
  });

  // Named dispatcher so cloud-local tools can recurse by name (GetDumpSection
  // fetches the formatted dump via RuntimeGetDumpById through this same path).
  // biome-ignore lint/suspicious/noExplicitAny: MCP tool args are untyped at this boundary
  async function invokeEmbeddedTool(name: string, args: any): Promise<unknown> {
    // Cloud-local tool: NOT in handlerMap, so branch BEFORE the unknown-tool
    // check. Principal-scoped via the ALS dumpScope; the raw login is never in
    // the key/log — only its hash.
    // Only intercept when core does NOT own this name — consistent with the
    // corpus/listTools dedupe where a future core GetDumpSection wins.
    if (name === 'GetDumpSection' && !handlerMap.has('GetDumpSection')) {
      const dumpScope = connectionALS.getStore()?.dumpScope;
      log.info('GetDumpSection dispatch', {
        destination: destinationName,
        principalHash: dumpScope?.principalHash,
        hasScope: !!dumpScope,
      });
      return handleGetDumpSectionCall(
        { dumpId: args?.dump_id, section: args?.section },
        {
          dumpScope,
          buffer: getDumpBuffer(),
          fetchFormatted: (id: string) =>
            invokeEmbeddedTool('RuntimeGetDumpById', {
              dump_id: id,
              view: 'formatted',
              response_mode: 'payload',
            }).then(parseFormattedDumpPayload),
        },
      );
    }

    const handler = handlerMap.get(name);
    if (!handler) {
      throw new Error(`Unknown MCP tool: ${name}`);
    }
    // Per-request connection override: if ALS has a connection, use it
    // instead of any shared/service-user destination connection.
    const requestScope = connectionALS.getStore();
    if (!requestScope) {
      throw new Error(
        `SAP credentials are required for destination "${destinationName}".`,
      );
    }
    const effectiveContext = requestScope.context;

    // For closure-based handlers, temporarily swap group.context
    // so they pick up per-request connection.
    let prevGroupContexts: HandlerContext[] | undefined;
    try {
      if (requestScope && handlerGroups) {
        prevGroupContexts = handlerGroups.map((g) => g.context);
        for (const g of handlerGroups) {
          g.context = effectiveContext;
        }
      }

      // Handlers from HandlerExporter have two signatures:
      // - length >= 2: (context, args) => ... (direct handlers)
      // - length === 1: (args) => ... (closure-based, uses group.context)
      // Match BaseMcpServer.registerHandlers() logic (line 283-301)
      const toolCall =
        handler.length >= 2
          ? handler(effectiveContext, args)
          : (handler as unknown as (a: typeof args) => unknown)(args);

      // No cloud-llm-hub-side timeout wrapper. Each SAP call is already bounded
      // by the adt-clients HTTP timeout (SAP_TIMEOUT_*), and destination
      // availability is covered by the ProbeDestination reachability check —
      // a redundant Promise.race here only fought those legitimate limits
      // (e.g. cutting heavy where-used scans that the ABAP layer allows).
      const result = await toolCall;

      const resultStr = JSON.stringify(result).slice(0, 1000);
      log.info('MCP tool call', {
        destination: destinationName,
        tool: name,
        handlerType: handler.length >= 2 ? 'direct' : 'closure',
        argsKeys: Object.keys(args || {}),
        args: JSON.stringify(args).slice(0, 300),
        resultLength: resultStr.length,
        resultPreview: resultStr.slice(0, 500),
        connectionOverride: !!requestScope,
      });
      return result;
    } catch (err) {
      log.error('MCP tool call failed', {
        tool: name,
        args: JSON.stringify(args).slice(0, 500),
        error: err instanceof Error ? err.message : String(err),
      });
      throw err;
    } finally {
      // Restore shared group.context after per-request override
      if (prevGroupContexts && handlerGroups) {
        for (let i = 0; i < handlerGroups.length; i++) {
          handlerGroups[i].context = prevGroupContexts[i];
        }
      }
    }
  }

  // Use embedded transport — direct in-process handler calls
  const mcpClient = new MCPClientWrapper({
    transport: 'embedded',
    listToolsHandler: async () => {
      const list = entries.map((e) => ({
        name: e.toolDefinition.name,
        description: e.toolDefinition.description,
        inputSchema: toJsonSchema(e.toolDefinition.inputSchema),
      }));
      // Append cloud-local GetDumpSection unless a core tool already claims the
      // name (same dedupe policy as the corpus). Its inputSchema is already a
      // JSON schema, so it is NOT run through toJsonSchema.
      if (!entries.some((e) => e.toolDefinition.name === 'GetDumpSection')) {
        const def = CLOUD_LOCAL_TOOLS[0];
        list.push({
          name: def.name,
          description: def.description ?? '',
          inputSchema: def.inputSchema as ReturnType<typeof toJsonSchema>,
        });
      }
      return list;
    },
    callToolHandler: async (name, args) => invokeEmbeddedTool(name, args),
  });

  // connect() populates internal tools list from listToolsHandler
  await mcpClient.connect();

  return new McpClientAdapter(mcpClient);
}

/** Create shared LLM instances (called once, reused across all agents) */
function getOrCreateSharedLlms(config: AgentConfig): {
  mainLlm: ReturnType<typeof makeLlm>;
  classifierLlm: ReturnType<typeof makeLlm>;
} {
  if (!sharedMainLlm) {
    const mainModel = getCurrentModel();
    sharedMainLlm = makeLlm(
      {
        provider: config.llm.provider,
        apiKey: config.llm.apiKey || 'sap-ai-sdk-managed',
        baseURL: config.llm.baseUrl,
        model: mainModel,
        temperature: config.llm.temperature,
        maxTokens: config.llm.maxTokens,
        resourceGroup: config.llm.resourceGroup,
      },
      config.llm.temperature,
    );
  }
  if (!sharedClassifierLlm) {
    const classifierModel =
      process.env.LLM_AGENT_CLASSIFIER_MODEL || config.llm.model;
    sharedClassifierLlm = makeLlm(
      {
        provider: config.llm.provider,
        apiKey: config.llm.apiKey || 'sap-ai-sdk-managed',
        baseURL: config.llm.baseUrl,
        model: classifierModel,
        maxTokens: config.llm.maxTokens,
        resourceGroup: config.llm.resourceGroup,
      },
      0.1,
    );
  }
  return {
    mainLlm: sharedMainLlm,
    classifierLlm: sharedClassifierLlm,
  };
}

/**
 * Shared builder configuration for destination-bound SmartAgents — the tool
 * loop, tool RAG, skills pool, MCP tools, and resilience/caching knobs common
 * to BOTH `buildAgentForDestination` (today's single coordinator-less agent)
 * and `buildExecutorWorker` (Task 7's coordinator-less executor worker), so
 * the two build paths cannot drift. Deliberately stops short of `.build()` —
 * callers add any build-specific wiring (e.g. `withRequestLogger`) and build.
 */
async function configureDestinationAgentBuilder(
  mcpAdapter: McpClientAdapter,
  toolsRag: ExpositionFilteringRag,
  config: AgentConfig,
  opts?: { skipSkills?: boolean },
): Promise<SmartAgentBuilder> {
  const { mainLlm: mainLlmPromise, classifierLlm: classifierLlmPromise } =
    getOrCreateSharedLlms(config);
  const mainLlm = await mainLlmPromise;
  const classifierLlm = await classifierLlmPromise;

  // Skip SAP AI SDK model validation for non-SAP providers (openai, anthropic, deepseek)
  const skipModelValidation = config.llm.provider !== 'sap-ai-sdk';

  const builder = new SmartAgentBuilder({
    skipModelValidation,
    agent: {
      maxIterations: config.agent.maxIterations,
      mode: config.agent.mode,
      historyRecencyWindow: config.agent.historyRecencyWindow,
      refreshToolsPerIteration: false,
      toolReselectPerIteration: true,
      ragQueryK: config.agent.ragQueryK,
      // Disable classifier — all input treated as action. Ensures tool search always runs.
      classificationEnabled: false,
    },
    prompts: {
      system: [
        'Use MCP tools when they can accomplish the task. Answer or fulfill requests when possible.',
        'When an action is impossible with available tools — say so and do not attempt it.',
        "Respond in the user's language. Code and object names always in English.",
      ].join('\n'),
      classifier: [
        'You are a Semantic Intent Analyzer. Decompose the user message into logical tasks.',
        'For each task, identify:',
        '  - "type": action (tasks, knowledge questions, SAP operations) or chat (greetings, math, jokes).',
        '  - "text": the actual task description.',
        '  - "context": "sap-abap" if SAP terms present, otherwise "general".',
        '  - "dependency": "independent" or "sequential".',
        '',
        'Rules:',
        '- Multi-step requests: split into separate "action" subprompts with "sequential" dependency.',
        '- Independent tasks: separate subprompts with "independent" dependency.',
        '- Knowledge/factual questions MUST be "action" — NOT "chat".',
        '- Requests to read, list, show, check, analyze, or get any data = "action".',
        '- Only greetings ("hi", "hello"), pure math, and jokes without data requests = "chat".',
        '',
        'Return ONLY a JSON array.',
      ].join('\n'),
    },
  })
    .withMainLlm(mainLlm)
    .withClassifierLlm(classifierLlm)
    .withMcpClients([mcpAdapter]);

  // Tools RAG store for MCP tool selection (auto-vectorized)
  builder.setToolsRag(toolsRag);

  // Mandatory skill pool. The builder vectorizes each skill into toolsRag as
  // `skill:<name>` = "Skill: <name>\n<description>" and the hardcoded flow
  // injects the matched skill's body into the system message. Wired here (agent
  // level), so chat and execute_step behave identically.
  //
  // Skipped when `opts.skipSkills` is set — the DAG controller build (see
  // `buildAgentForDestination`) has its tool-loop stage gated off whenever a
  // coordinator is active (`default-pipeline.js`: `{id:'tool-loop',
  // when:'!coordinatorActive'}`), so the controller never consults skills.
  // Vectorizing them there is a wasted real embedding call (18 skills) on
  // every destination init and regresses cold-start; the executor worker
  // (which DOES run the tool-loop) keeps skills enabled.
  if (!opts?.skipSkills) {
    const skillsPool = buildSkillsPool();
    builder.withSkillManager(skillsPool);
    await logSkillsPool(skillsPool);
  }

  // Share embedder across all RAG queries
  if (sharedEmbedder) builder.withEmbedder(sharedEmbedder);

  builder
    .withClassification(false) // Disable classifier — treat all input as action.
    // Classifier caused tool selection to be skipped for "chat" queries.
    // Without classifier, RAG query + tool selection always runs.
    .withLlmCallStrategy(new FallbackLlmCallStrategy())
    .withToolReselection(true)
    .withToolCache(new ToolCache({ ttlMs: 30_000 }))
    .withMetrics(metrics)
    .withSessionManager(new SessionManager({ tokenBudget: 8000 }))
    .withHistorySummarization(20)
    .withClientAdapter(new ClineClientAdapter());

  // Default hardcoded flow — matches PoC for minimal token overhead.
  // Tools store wrapped with ExpositionFilteringRag to strip ragFilter
  // (tools have no namespace, but opts carry ragFilter for user isolation).

  return builder;
}

/**
 * Build a SmartAgent for a specific destination.
 * Shares LLM, embedder, facts/feedback/state RAG, metrics across all agents.
 */
export async function buildAgentForDestination(
  mcpAdapter: McpClientAdapter,
  toolsRag: ExpositionFilteringRag,
  config: AgentConfig,
): Promise<SmartAgentHandle> {
  const log = cds.log('agent-manager');

  // Self-contained per-trace logger (Task 2) — a plain `DefaultRequestLogger`
  // would wipe telemetry on the nested controller->worker `startRequest` call
  // (Verified fact 10). The SAME instance is injected into the executor
  // worker AND the finalizer so the finalizer's ground truth reflects the
  // tools the worker actually executed (Verified fact 9).
  const recLogger = new RecordingRequestLogger();
  const executorWorker = await buildExecutorWorker(
    mcpAdapter,
    toolsRag,
    config,
    recLogger,
  );

  // Same shared main LLM the rest of the destination agent uses — no extra
  // provider client stood up just for the critic layer.
  const { mainLlm: mainLlmPromise } = getOrCreateSharedLlms(config);
  const criticLlm = await mainLlmPromise;

  // Controller build skips skills — its tool-loop stage is gated off
  // whenever the DAG coordinator is active, so the controller never
  // consults the skills pool (see `configureDestinationAgentBuilder`).
  // Only the executor worker above needs the real skill vectorization.
  const builder = await configureDestinationAgentBuilder(
    mcpAdapter,
    toolsRag,
    config,
    { skipSkills: true },
  );

  builder.withRequestLogger(recLogger).withDagCoordinator({
    planner: new FixedExecutorPlanner(),
    interpreter: new DagPlanInterpreter(),
    // Key MUST be 'executor' — FixedExecutorPlanner hardcodes `agent:
    // 'executor'` on the single DAG node; a mismatched key makes the
    // interpreter throw PLAN_INVALID.
    workers: new Map([['executor', executorWorker]]),
    // Reads the SAME recLogger the worker was built with.
    finalizer: new NoticeFinalizer(recLogger, criticLlm),
    // errorStrategy omitted -> AbortErrorStrategy default;
    // reviewer omitted -> no plan-gate (NoopReviewStrategy default).
  });

  const handle = await builder.build();

  // Expose the recLogger on the handle so channel handlers (Task 11) can
  // call `recLogger.dropRequest(traceId)` in their `finally` block — nobody
  // else drops it, so the per-trace bucket would otherwise leak.
  (
    handle as SmartAgentHandle & { recLogger?: RecordingRequestLogger }
  ).recLogger = recLogger;

  // Diagnostic: confirm structured pipeline is active
  // biome-ignore lint/suspicious/noExplicitAny: diagnostic access to private fields
  const agentObj = handle.agent as any;
  log.info('SmartAgent pipeline diagnostic', {
    hasPipelineExecutor: !!agentObj.pipelineExecutor,
    hasPipelineStages: !!agentObj.pipelineStages,
    stageCount: agentObj.pipelineStages?.length ?? 0,
    stageIds: agentObj.pipelineStages?.map((s: { id: string }) => s.id) ?? [],
    ragStoreKeys: Object.keys(handle.ragStores),
    refreshToolsPerIteration: agentObj.config?.refreshToolsPerIteration,
    toolReselectPerIteration: agentObj.config?.toolReselectPerIteration,
    ragQueryK: agentObj.config?.ragQueryK,
    hasDagCoordinator: true,
  });

  return handle;
}

/**
 * Build the coordinator-less executor worker (Task 7) — the SAME tool-loop
 * SmartAgent configuration as `buildAgentForDestination` (via the shared
 * `configureDestinationAgentBuilder` helper), MINUS any coordinator, PLUS
 * `withRequestLogger(recLogger)` so the worker's internal ABAP tool calls
 * land in the shared `RecordingRequestLogger` (Verified fact 9 —
 * `SmartAgentSubAgent.run` does not forward a requestLogger to the wrapped
 * agent, so it must be injected at build time). Wrapped as an `ISubAgent` by
 * reusing the library's own `SmartAgentSubAgent` — no bespoke wrapper.
 */
export async function buildExecutorWorker(
  mcpAdapter: McpClientAdapter,
  toolsRag: ExpositionFilteringRag,
  config: AgentConfig,
  recLogger: IRequestLogger,
): Promise<ISubAgent> {
  const builder = await configureDestinationAgentBuilder(
    mcpAdapter,
    toolsRag,
    config,
  );
  builder.withRequestLogger(recLogger);

  const handle = await builder.build();
  return new SmartAgentSubAgent('executor', handle.agent);
}

/**
 * Build a SmartAgent without MCP tools — LLM-only mode.
 * Used as fallback when no SAP destinations are available.
 */
async function buildLlmOnlyAgent(
  config: AgentConfig,
): Promise<SmartAgentHandle> {
  const log = cds.log('agent-manager');
  const { mainLlm: mainLlmPromise, classifierLlm: classifierLlmPromise } =
    getOrCreateSharedLlms(config);
  const mainLlm = await mainLlmPromise;
  const classifierLlm = await classifierLlmPromise;

  const builder = new SmartAgentBuilder({
    skipModelValidation: config.llm.provider !== 'sap-ai-sdk',
    agent: {
      maxIterations: 1,
      mode: config.agent.mode,
      historyRecencyWindow: config.agent.historyRecencyWindow,
      refreshToolsPerIteration: false,
      toolReselectPerIteration: false,
      ragQueryK: 0,
      classificationEnabled: false,
    },
    prompts: {
      system: [
        'You are a helpful AI assistant. No MCP tools are available — SAP system destinations are not configured or unreachable.',
        'Answer questions using your knowledge. If the user asks to perform SAP operations, explain that SAP connectivity is not available.',
        "Respond in the user's language. Code and object names always in English.",
      ].join('\n'),
    },
  })
    .withMainLlm(mainLlm)
    .withClassifierLlm(classifierLlm)
    .withClassification(false)
    .withLlmCallStrategy(new FallbackLlmCallStrategy())
    .withMetrics(metrics)
    .withSessionManager(new SessionManager({ tokenBudget: 8000 }))
    .withHistorySummarization(20)
    .withClientAdapter(new ClineClientAdapter());

  if (sharedEmbedder) builder.withEmbedder(sharedEmbedder);

  const handle = await builder.build();
  log.info('LLM-only agent built (no MCP tools)');
  return handle;
}

/**
 * Get SmartAgent handle for a destination.
 *
 * Each destination has its own SmartAgent with isolated MCP connection.
 * Shared resources: LLM, embedder, facts/feedback/state RAG, metrics.
 */
/**
 * How long `getSmartAgent` waits for a destination's lazy vectorization before
 * giving up. Env `LLM_AGENT_DESTINATION_INIT_WAIT_MS`; malformed/≤0 → 90 s.
 */
export function getDestinationInitWaitMs(
  env: NodeJS.ProcessEnv = process.env,
): number {
  const v = Number(env.LLM_AGENT_DESTINATION_INIT_WAIT_MS);
  return Number.isFinite(v) && v > 0 ? v : 90_000;
}

export async function getSmartAgent(
  requestedModel?: string,
  requestedDestination?: string,
): Promise<SmartAgentHandle> {
  const log = cds.log('agent-manager');
  const config = getAgentConfig();

  // --- Model hot-swap (updates all agents — LLM is stateless) ---
  // NOT gated on agentHandles.size: with no blocking primary at startup, the
  // FIRST real request can arrive before any agent exists. We still must set
  // currentModel/sharedMainLlm so the about-to-be-built first agent uses the
  // requested model (getOrCreateSharedLlms reuses sharedMainLlm). The loop over
  // existing handles is simply a no-op when none exist yet.
  const activeModel = getCurrentModel();
  if (requestedModel && requestedModel !== activeModel) {
    const newLlmPromise = makeLlm(
      {
        provider: config.llm.provider,
        apiKey: config.llm.apiKey || 'sap-ai-sdk-managed',
        baseURL: config.llm.baseUrl,
        model: requestedModel,
        temperature: config.llm.temperature,
        maxTokens: config.llm.maxTokens,
        resourceGroup: config.llm.resourceGroup,
      },
      config.llm.temperature,
    );
    const newLlm = await newLlmPromise;

    for (const handle of agentHandles.values()) {
      // biome-ignore lint/suspicious/noExplicitAny: accessing internal deps for model hot-swap
      (handle.agent as any).deps.mainLlm = newLlm;
    }
    sharedMainLlm = newLlmPromise;
    currentModel = requestedModel;

    log.info('Model set for request', {
      from: activeModel,
      to: requestedModel,
      agentCount: agentHandles.size,
    });
  }

  // --- Destination lookup (no hot-swap — each dest has its own agent) ---
  const destName = requestedDestination || config.mcp.destination;
  const isExplicit = !!requestedDestination;
  const allowFallback =
    process.env.LLM_AGENT_ALLOW_LLM_ONLY_FALLBACK === 'true';

  // Ready → serve immediately.
  let handle = agentHandles.get(destName);
  if (handle) {
    return handle;
  }

  // Nothing configured at all → LLM-only (there is genuinely nothing to wait
  // for). This is not the "explicit destination not ready" case.
  if (!destName) {
    if (!llmOnlyHandle) {
      llmOnlyHandle = await buildLlmOnlyAgent(config);
    }
    return llmOnlyHandle;
  }

  const isTerminal = (s?: string) => s === 'error' || s === 'unreachable';

  // Not ready and not terminal (absent / unknown / pending / vectorizing):
  // WAIT for this destination's vectorization instead of erroring. All callers
  // share one init via ensureDestinationInit; the wait is bounded by
  // LLM_AGENT_DESTINATION_INIT_WAIT_MS so a hung destination can't hold the
  // request forever. This replaces the old immediate "agent not initialized".
  if (!isTerminal(destinationStates.get(destName)?.status)) {
    const waitMs = getDestinationInitWaitMs();
    log.info('Destination not ready — waiting for vectorization', {
      destination: destName,
      status: destinationStates.get(destName)?.status ?? 'unknown',
      waitMs,
    });
    await Promise.race([
      // Swallow init errors here; the state re-read below decides the outcome.
      ensureDestinationInit(destName).catch(() => undefined),
      new Promise((resolve) => setTimeout(resolve, waitMs)),
    ]);
    handle = agentHandles.get(destName);
    if (handle) {
      return handle;
    }
  }

  // Still not ready after the wait: timed out (still vectorizing) or terminal
  // (error/unreachable). Fail fast for an explicit destination — silently
  // degrading to LLM-only would fabricate an answer from training data instead
  // of hitting the caller's SAP system (issue #83). Non-explicit requests get
  // LLM-only ONLY with the escape hatch (LLM_AGENT_ALLOW_LLM_ONLY_FALLBACK);
  // otherwise they also throw a retryable 503 (the init keeps running, so a
  // retry shortly after usually succeeds).
  const destState = destinationStates.get(destName);
  const status = destState?.status ?? 'unknown';

  if (isExplicit || !allowFallback) {
    const detail = isTerminal(status)
      ? destState?.error || status
      : `still initializing after ${Math.round(getDestinationInitWaitMs() / 1000)}s — retry shortly`;
    const destError = new Error(
      `Destination "${destName}" is ${status}: ${detail}`,
    ) as Error & {
      statusCode?: number;
      code?: string;
      destinationStatus?: string;
      destination?: string;
    };
    destError.statusCode = 503;
    destError.code = 'destination_unreachable';
    destError.destinationStatus = status;
    destError.destination = destName;
    log.warn('Destination not ready after wait — refusing LLM-only fallback', {
      destination: destName,
      status,
      explicit: isExplicit,
    });
    throw destError;
  }

  // Non-explicit + escape hatch → legacy permissive LLM-only.
  log.warn('Destination not ready after wait — using LLM-only fallback', {
    destination: destName,
    status,
  });
  if (!llmOnlyHandle) {
    llmOnlyHandle = await buildLlmOnlyAgent(config);
  }
  return llmOnlyHandle;
}

/**
 * Bootstrap the agent layer. Readiness does NOT depend on any destination:
 * the app is ready as soon as the process is up (shared LLMs init lazily on
 * first agent build). ALL destinations warm in the background and/or on demand
 * — there is no privileged, blocking "primary". A request to a not-yet-ready
 * destination waits (bounded) in getSmartAgent instead of erroring.
 * Called once from server.ts on startup.
 */
export async function initSmartAgents(): Promise<void> {
  const log = cds.log('agent-manager');
  initDestinationMapping();
  const config = getAgentConfig();
  const destName = config.mcp.destination;

  // LLM-only mode: no MCP destination configured at all.
  if (!destName) {
    log.info('No MCP destination configured — starting in LLM-only mode', {
      model: getCurrentModel(),
      mode: config.agent.mode,
    });
    llmOnlyHandle = await buildLlmOnlyAgent(config);
    initializationDone = true;
    return;
  }

  // Ready immediately — no blocking destination init. (Removing the primary
  // fixes: broken primary degrading startup, and non-primary destinations
  // erroring for minutes after every deploy.)
  initializationDone = true;
  log.info('SmartAgents ready — destinations warm in background/on-demand', {
    model: getCurrentModel(),
    embeddingModel:
      process.env.LLM_AGENT_EMBEDDING_MODEL || 'text-embedding-3-small',
    mode: config.agent.mode,
    warmFirst: destName,
  });

  // Background: build the shared tool corpus ONCE (fire-and-forget — readiness
  // does not wait on it; getSmartAgent/initDestination await it on the request
  // path via the bounded wait). Then warm ALL SAP destinations (the configured
  // one first as a non-privileged hint). Non-blocking — never gates readiness.
  ensureSharedToolsVectorized().catch((err) => {
    log.warn('Shared tool corpus build error', {
      error: err instanceof Error ? err.message : String(err),
    });
  });
  initBackgroundDestinations().catch((err) => {
    log.warn('Background destination warmup error', {
      error: err instanceof Error ? err.message : String(err),
    });
  });
}

/**
 * Gracefully close all SmartAgents (call on shutdown)
 */
export async function closeSmartAgent(): Promise<void> {
  const log = cds.log('agent-manager');
  for (const [dest, handle] of agentHandles) {
    log.info('Closing SmartAgent', { destination: dest });
    await handle.close().catch((err) => {
      log.warn('Failed to close SmartAgent', {
        destination: dest,
        error: String(err),
      });
    });
  }
  agentHandles.clear();
}
