/**
 * Regenerate the committed tool → exposition snapshot.
 *
 *   npx tsx tools/generate-tool-exposition.ts
 *
 * The snapshot is what `test/unit/tool-exposition-snapshot.test.ts` compares
 * against. It exists so that a change to who can run what shows up as a DIFF in
 * review, instead of happening quietly when an upstream package moves a tool
 * between groups.
 *
 * Regenerating is not approval. Read the diff: a tool moving from `high` to
 * `readonly` widens what a reader may execute.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { CLOUD_LOCAL_TOOL_EXPOSITIONS } from '../srv/lib/cloud-local-tools';
import { resolveExposition } from '../srv/lib/exposition';
import { buildToolExpositionMap } from '../srv/lib/tool-exposition-map';

const OUT = join(__dirname, '..', 'test', 'fixtures', 'tool-exposition.json');

const map = buildToolExpositionMap(CLOUD_LOCAL_TOOL_EXPOSITIONS);
const reader = new Set(resolveExposition(['MCP_Reader']));
const developer = new Set(resolveExposition(['MCP_Developer']));

const tools: Record<string, string> = {};
for (const name of [...map.keys()].sort()) {
  tools[name] = map.get(name) as string;
}

const counts: Record<string, number> = {};
for (const level of Object.values(tools)) {
  counts[level] = (counts[level] ?? 0) + 1;
}

const reachable = (allowed: Set<string>) =>
  Object.values(tools).filter((l) => allowed.has(l)).length;

writeFileSync(
  OUT,
  `${JSON.stringify(
    {
      _comment:
        "Generated by tools/generate-tool-exposition.ts. A diff here changes who may execute what — read it, do not just accept it. Counts are what a ROLE permits; the server additionally drops tools whose available_in does not match the destination's system type, so tools/list returns at most these numbers.",
      totals: {
        tools: Object.keys(tools).length,
        byLevel: counts,
        reachableByReader: reachable(reader),
        reachableByDeveloper: reachable(developer),
      },
      tools,
    },
    null,
    2,
  )}\n`,
);

console.log(`Wrote ${Object.keys(tools).length} tools to ${OUT}`);
console.log('  by level:', counts);
console.log(
  `  reader reaches ${reachable(reader)}, developer reaches ${reachable(developer)}`,
);
